gradle ModelTest -PXargs="../share/test_folds/$1_test_0.txt ../system/$1_model_0.txt_$2_$3 $4 xQuAD"
gradle ModelTest -PXargs="../share/test_folds/$1_test_1.txt ../system/$1_model_1.txt_$2_$3 $4 xQuAD"
gradle ModelTest -PXargs="../share/test_folds/$1_test_2.txt ../system/$1_model_2.txt_$2_$3 $4 xQuAD"
gradle ModelTest -PXargs="../share/test_folds/$1_test_3.txt ../system/$1_model_3.txt_$2_$3 $4 xQuAD"
gradle ModelTest -PXargs="../share/test_folds/$1_test_4.txt ../system/$1_model_4.txt_$2_$3 $4 xQuAD"
