// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public interface DocumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learner.Document)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
