// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

/**
 * Protobuf type {@code learner.Label}
 */
public  final class Label extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:learner.Label)
    LabelOrBuilder {
  // Use Label.newBuilder() to construct.
  private Label(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Label() {
    id_ = 0;
    labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Label(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              labels_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            labels_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              content_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            content_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        labels_ = labels_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        content_ = content_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_Label_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_Label_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufmg.dcc.latin.grpc.learner.Label.class, br.ufmg.dcc.latin.grpc.learner.Label.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int LABELS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList labels_;
  /**
   * <code>repeated string labels = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getLabelsList() {
    return labels_;
  }
  /**
   * <code>repeated string labels = 2;</code>
   */
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <code>repeated string labels = 2;</code>
   */
  public java.lang.String getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <code>repeated string labels = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLabelsBytes(int index) {
    return labels_.getByteString(index);
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList content_;
  /**
   * <code>repeated string content = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getContentList() {
    return content_;
  }
  /**
   * <code>repeated string content = 3;</code>
   */
  public int getContentCount() {
    return content_.size();
  }
  /**
   * <code>repeated string content = 3;</code>
   */
  public java.lang.String getContent(int index) {
    return content_.get(index);
  }
  /**
   * <code>repeated string content = 3;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes(int index) {
    return content_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, labels_.getRaw(i));
    }
    for (int i = 0; i < content_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, content_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < labels_.size(); i++) {
        dataSize += computeStringSizeNoTag(labels_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLabelsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < content_.size(); i++) {
        dataSize += computeStringSizeNoTag(content_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getContentList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.Label parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufmg.dcc.latin.grpc.learner.Label prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code learner.Label}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:learner.Label)
      br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_Label_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_Label_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufmg.dcc.latin.grpc.learner.Label.class, br.ufmg.dcc.latin.grpc.learner.Label.Builder.class);
    }

    // Construct using br.ufmg.dcc.latin.grpc.learner.Label.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_Label_descriptor;
    }

    public br.ufmg.dcc.latin.grpc.learner.Label getDefaultInstanceForType() {
      return br.ufmg.dcc.latin.grpc.learner.Label.getDefaultInstance();
    }

    public br.ufmg.dcc.latin.grpc.learner.Label build() {
      br.ufmg.dcc.latin.grpc.learner.Label result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public br.ufmg.dcc.latin.grpc.learner.Label buildPartial() {
      br.ufmg.dcc.latin.grpc.learner.Label result = new br.ufmg.dcc.latin.grpc.learner.Label(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        labels_ = labels_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.labels_ = labels_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        content_ = content_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.content_ = content_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufmg.dcc.latin.grpc.learner.Label) {
        return mergeFrom((br.ufmg.dcc.latin.grpc.learner.Label)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufmg.dcc.latin.grpc.learner.Label other) {
      if (other == br.ufmg.dcc.latin.grpc.learner.Label.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.labels_.isEmpty()) {
        if (labels_.isEmpty()) {
          labels_ = other.labels_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureLabelsIsMutable();
          labels_.addAll(other.labels_);
        }
        onChanged();
      }
      if (!other.content_.isEmpty()) {
        if (content_.isEmpty()) {
          content_ = other.content_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureContentIsMutable();
          content_.addAll(other.content_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufmg.dcc.latin.grpc.learner.Label parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufmg.dcc.latin.grpc.learner.Label) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLabelsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        labels_ = new com.google.protobuf.LazyStringArrayList(labels_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getLabelsList() {
      return labels_.getUnmodifiableView();
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public java.lang.String getLabels(int index) {
      return labels_.get(index);
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelsBytes(int index) {
      return labels_.getByteString(index);
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public Builder setLabels(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLabelsIsMutable();
      labels_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public Builder addLabels(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLabelsIsMutable();
      labels_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public Builder addAllLabels(
        java.lang.Iterable<java.lang.String> values) {
      ensureLabelsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, labels_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public Builder clearLabels() {
      labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 2;</code>
     */
    public Builder addLabelsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureLabelsIsMutable();
      labels_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureContentIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        content_ = new com.google.protobuf.LazyStringArrayList(content_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getContentList() {
      return content_.getUnmodifiableView();
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public java.lang.String getContent(int index) {
      return content_.get(index);
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes(int index) {
      return content_.getByteString(index);
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public Builder setContent(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContentIsMutable();
      content_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public Builder addContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContentIsMutable();
      content_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public Builder addAllContent(
        java.lang.Iterable<java.lang.String> values) {
      ensureContentIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, content_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public Builder clearContent() {
      content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string content = 3;</code>
     */
    public Builder addContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureContentIsMutable();
      content_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:learner.Label)
  }

  // @@protoc_insertion_point(class_scope:learner.Label)
  private static final br.ufmg.dcc.latin.grpc.learner.Label DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufmg.dcc.latin.grpc.learner.Label();
  }

  public static br.ufmg.dcc.latin.grpc.learner.Label getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Label>
      PARSER = new com.google.protobuf.AbstractParser<Label>() {
    public Label parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Label(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Label> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Label> getParserForType() {
    return PARSER;
  }

  public br.ufmg.dcc.latin.grpc.learner.Label getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

