// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public interface LabelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learner.Label)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>repeated string labels = 2;</code>
   */
  com.google.protobuf.ProtocolStringList
      getLabelsList();
  /**
   * <code>repeated string labels = 2;</code>
   */
  int getLabelsCount();
  /**
   * <code>repeated string labels = 2;</code>
   */
  java.lang.String getLabels(int index);
  /**
   * <code>repeated string labels = 2;</code>
   */
  com.google.protobuf.ByteString
      getLabelsBytes(int index);

  /**
   * <code>repeated string content = 3;</code>
   */
  com.google.protobuf.ProtocolStringList
      getContentList();
  /**
   * <code>repeated string content = 3;</code>
   */
  int getContentCount();
  /**
   * <code>repeated string content = 3;</code>
   */
  java.lang.String getContent(int index);
  /**
   * <code>repeated string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes(int index);
}
