// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public final class LearnerProto {
  private LearnerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learner_LoadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_learner_LoadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learner_Document_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_learner_Document_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learner_LoadReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_learner_LoadReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learner_SimilarityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_learner_SimilarityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learner_Label_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_learner_Label_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_learner_SimilarityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_learner_SimilarityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlearner.proto\022\007learner\"3\n\013LoadRequest\022" +
      "$\n\tdocuments\030\001 \003(\0132\021.learner.Document\"\'\n" +
      "\010Document\022\n\n\002id\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\"\033" +
      "\n\tLoadReply\022\016\n\006status\030\001 \001(\t\"3\n\021Similarit" +
      "yRequest\022\036\n\006labels\030\001 \003(\0132\016.learner.Label" +
      "\"4\n\005Label\022\n\n\002id\030\001 \001(\005\022\016\n\006labels\030\002 \003(\t\022\017\n" +
      "\007content\030\003 \003(\t\"B\n\022SimilarityResponse\022\014\n\004" +
      "rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005\022\020\n\004data\030\003 \003(\001B\002" +
      "\020\0012\213\001\n\007Learner\0222\n\004load\022\024.learner.LoadReq" +
      "uest\032\022.learner.LoadReply\"\000\022L\n\017getSimilar",
      "ities\022\032.learner.SimilarityRequest\032\033.lear" +
      "ner.SimilarityResponse\"\000B0\n\036br.ufmg.dcc." +
      "latin.grpc.learnerB\014LearnerProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_learner_LoadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_learner_LoadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_learner_LoadRequest_descriptor,
        new java.lang.String[] { "Documents", });
    internal_static_learner_Document_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_learner_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_learner_Document_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_learner_LoadReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_learner_LoadReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_learner_LoadReply_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_learner_SimilarityRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_learner_SimilarityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_learner_SimilarityRequest_descriptor,
        new java.lang.String[] { "Labels", });
    internal_static_learner_Label_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_learner_Label_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_learner_Label_descriptor,
        new java.lang.String[] { "Id", "Labels", "Content", });
    internal_static_learner_SimilarityResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_learner_SimilarityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_learner_SimilarityResponse_descriptor,
        new java.lang.String[] { "Rows", "Cols", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
