// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public interface LoadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learner.LoadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  java.util.List<br.ufmg.dcc.latin.grpc.learner.Document> 
      getDocumentsList();
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  br.ufmg.dcc.latin.grpc.learner.Document getDocuments(int index);
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  int getDocumentsCount();
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  java.util.List<? extends br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder> 
      getDocumentsOrBuilderList();
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder getDocumentsOrBuilder(
      int index);
}
