// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

/**
 * Protobuf type {@code learner.LoadRequest}
 */
public  final class LoadRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:learner.LoadRequest)
    LoadRequestOrBuilder {
  // Use LoadRequest.newBuilder() to construct.
  private LoadRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LoadRequest() {
    documents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LoadRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              documents_ = new java.util.ArrayList<br.ufmg.dcc.latin.grpc.learner.Document>();
              mutable_bitField0_ |= 0x00000001;
            }
            documents_.add(input.readMessage(br.ufmg.dcc.latin.grpc.learner.Document.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        documents_ = java.util.Collections.unmodifiableList(documents_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_LoadRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_LoadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufmg.dcc.latin.grpc.learner.LoadRequest.class, br.ufmg.dcc.latin.grpc.learner.LoadRequest.Builder.class);
  }

  public static final int DOCUMENTS_FIELD_NUMBER = 1;
  private java.util.List<br.ufmg.dcc.latin.grpc.learner.Document> documents_;
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  public java.util.List<br.ufmg.dcc.latin.grpc.learner.Document> getDocumentsList() {
    return documents_;
  }
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  public java.util.List<? extends br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder> 
      getDocumentsOrBuilderList() {
    return documents_;
  }
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  public int getDocumentsCount() {
    return documents_.size();
  }
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  public br.ufmg.dcc.latin.grpc.learner.Document getDocuments(int index) {
    return documents_.get(index);
  }
  /**
   * <code>repeated .learner.Document documents = 1;</code>
   */
  public br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder getDocumentsOrBuilder(
      int index) {
    return documents_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < documents_.size(); i++) {
      output.writeMessage(1, documents_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < documents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, documents_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufmg.dcc.latin.grpc.learner.LoadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code learner.LoadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:learner.LoadRequest)
      br.ufmg.dcc.latin.grpc.learner.LoadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_LoadRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_LoadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufmg.dcc.latin.grpc.learner.LoadRequest.class, br.ufmg.dcc.latin.grpc.learner.LoadRequest.Builder.class);
    }

    // Construct using br.ufmg.dcc.latin.grpc.learner.LoadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDocumentsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (documentsBuilder_ == null) {
        documents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        documentsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_LoadRequest_descriptor;
    }

    public br.ufmg.dcc.latin.grpc.learner.LoadRequest getDefaultInstanceForType() {
      return br.ufmg.dcc.latin.grpc.learner.LoadRequest.getDefaultInstance();
    }

    public br.ufmg.dcc.latin.grpc.learner.LoadRequest build() {
      br.ufmg.dcc.latin.grpc.learner.LoadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public br.ufmg.dcc.latin.grpc.learner.LoadRequest buildPartial() {
      br.ufmg.dcc.latin.grpc.learner.LoadRequest result = new br.ufmg.dcc.latin.grpc.learner.LoadRequest(this);
      int from_bitField0_ = bitField0_;
      if (documentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          documents_ = java.util.Collections.unmodifiableList(documents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.documents_ = documents_;
      } else {
        result.documents_ = documentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufmg.dcc.latin.grpc.learner.LoadRequest) {
        return mergeFrom((br.ufmg.dcc.latin.grpc.learner.LoadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufmg.dcc.latin.grpc.learner.LoadRequest other) {
      if (other == br.ufmg.dcc.latin.grpc.learner.LoadRequest.getDefaultInstance()) return this;
      if (documentsBuilder_ == null) {
        if (!other.documents_.isEmpty()) {
          if (documents_.isEmpty()) {
            documents_ = other.documents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDocumentsIsMutable();
            documents_.addAll(other.documents_);
          }
          onChanged();
        }
      } else {
        if (!other.documents_.isEmpty()) {
          if (documentsBuilder_.isEmpty()) {
            documentsBuilder_.dispose();
            documentsBuilder_ = null;
            documents_ = other.documents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            documentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getDocumentsFieldBuilder() : null;
          } else {
            documentsBuilder_.addAllMessages(other.documents_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufmg.dcc.latin.grpc.learner.LoadRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufmg.dcc.latin.grpc.learner.LoadRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<br.ufmg.dcc.latin.grpc.learner.Document> documents_ =
      java.util.Collections.emptyList();
    private void ensureDocumentsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        documents_ = new java.util.ArrayList<br.ufmg.dcc.latin.grpc.learner.Document>(documents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        br.ufmg.dcc.latin.grpc.learner.Document, br.ufmg.dcc.latin.grpc.learner.Document.Builder, br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder> documentsBuilder_;

    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public java.util.List<br.ufmg.dcc.latin.grpc.learner.Document> getDocumentsList() {
      if (documentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(documents_);
      } else {
        return documentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public int getDocumentsCount() {
      if (documentsBuilder_ == null) {
        return documents_.size();
      } else {
        return documentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Document getDocuments(int index) {
      if (documentsBuilder_ == null) {
        return documents_.get(index);
      } else {
        return documentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder setDocuments(
        int index, br.ufmg.dcc.latin.grpc.learner.Document value) {
      if (documentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentsIsMutable();
        documents_.set(index, value);
        onChanged();
      } else {
        documentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder setDocuments(
        int index, br.ufmg.dcc.latin.grpc.learner.Document.Builder builderForValue) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.set(index, builderForValue.build());
        onChanged();
      } else {
        documentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder addDocuments(br.ufmg.dcc.latin.grpc.learner.Document value) {
      if (documentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentsIsMutable();
        documents_.add(value);
        onChanged();
      } else {
        documentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder addDocuments(
        int index, br.ufmg.dcc.latin.grpc.learner.Document value) {
      if (documentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentsIsMutable();
        documents_.add(index, value);
        onChanged();
      } else {
        documentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder addDocuments(
        br.ufmg.dcc.latin.grpc.learner.Document.Builder builderForValue) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.add(builderForValue.build());
        onChanged();
      } else {
        documentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder addDocuments(
        int index, br.ufmg.dcc.latin.grpc.learner.Document.Builder builderForValue) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.add(index, builderForValue.build());
        onChanged();
      } else {
        documentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder addAllDocuments(
        java.lang.Iterable<? extends br.ufmg.dcc.latin.grpc.learner.Document> values) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, documents_);
        onChanged();
      } else {
        documentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder clearDocuments() {
      if (documentsBuilder_ == null) {
        documents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        documentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public Builder removeDocuments(int index) {
      if (documentsBuilder_ == null) {
        ensureDocumentsIsMutable();
        documents_.remove(index);
        onChanged();
      } else {
        documentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Document.Builder getDocumentsBuilder(
        int index) {
      return getDocumentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder getDocumentsOrBuilder(
        int index) {
      if (documentsBuilder_ == null) {
        return documents_.get(index);  } else {
        return documentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public java.util.List<? extends br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder> 
         getDocumentsOrBuilderList() {
      if (documentsBuilder_ != null) {
        return documentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(documents_);
      }
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Document.Builder addDocumentsBuilder() {
      return getDocumentsFieldBuilder().addBuilder(
          br.ufmg.dcc.latin.grpc.learner.Document.getDefaultInstance());
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Document.Builder addDocumentsBuilder(
        int index) {
      return getDocumentsFieldBuilder().addBuilder(
          index, br.ufmg.dcc.latin.grpc.learner.Document.getDefaultInstance());
    }
    /**
     * <code>repeated .learner.Document documents = 1;</code>
     */
    public java.util.List<br.ufmg.dcc.latin.grpc.learner.Document.Builder> 
         getDocumentsBuilderList() {
      return getDocumentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        br.ufmg.dcc.latin.grpc.learner.Document, br.ufmg.dcc.latin.grpc.learner.Document.Builder, br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder> 
        getDocumentsFieldBuilder() {
      if (documentsBuilder_ == null) {
        documentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            br.ufmg.dcc.latin.grpc.learner.Document, br.ufmg.dcc.latin.grpc.learner.Document.Builder, br.ufmg.dcc.latin.grpc.learner.DocumentOrBuilder>(
                documents_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        documents_ = null;
      }
      return documentsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:learner.LoadRequest)
  }

  // @@protoc_insertion_point(class_scope:learner.LoadRequest)
  private static final br.ufmg.dcc.latin.grpc.learner.LoadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufmg.dcc.latin.grpc.learner.LoadRequest();
  }

  public static br.ufmg.dcc.latin.grpc.learner.LoadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoadRequest>
      PARSER = new com.google.protobuf.AbstractParser<LoadRequest>() {
    public LoadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoadRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoadRequest> getParserForType() {
    return PARSER;
  }

  public br.ufmg.dcc.latin.grpc.learner.LoadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

