// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public interface LoadReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learner.LoadReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>optional string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
