// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

/**
 * Protobuf type {@code learner.SimilarityResponse}
 */
public  final class SimilarityResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:learner.SimilarityResponse)
    SimilarityResponseOrBuilder {
  // Use SimilarityResponse.newBuilder() to construct.
  private SimilarityResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SimilarityResponse() {
    rows_ = 0;
    cols_ = 0;
    data_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SimilarityResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            rows_ = input.readInt32();
            break;
          }
          case 16: {

            cols_ = input.readInt32();
            break;
          }
          case 25: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              data_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000004;
            }
            data_.add(input.readDouble());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              data_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              data_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.class, br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ROWS_FIELD_NUMBER = 1;
  private int rows_;
  /**
   * <code>optional int32 rows = 1;</code>
   */
  public int getRows() {
    return rows_;
  }

  public static final int COLS_FIELD_NUMBER = 2;
  private int cols_;
  /**
   * <code>optional int32 cols = 2;</code>
   */
  public int getCols() {
    return cols_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Double> data_;
  /**
   * <code>repeated double data = 3 [packed = true];</code>
   */
  public java.util.List<java.lang.Double>
      getDataList() {
    return data_;
  }
  /**
   * <code>repeated double data = 3 [packed = true];</code>
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <code>repeated double data = 3 [packed = true];</code>
   */
  public double getData(int index) {
    return data_.get(index);
  }
  private int dataMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (rows_ != 0) {
      output.writeInt32(1, rows_);
    }
    if (cols_ != 0) {
      output.writeInt32(2, cols_);
    }
    if (getDataList().size() > 0) {
      output.writeRawVarint32(26);
      output.writeRawVarint32(dataMemoizedSerializedSize);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeDoubleNoTag(data_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rows_);
    }
    if (cols_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cols_);
    }
    {
      int dataSize = 0;
      dataSize = 8 * getDataList().size();
      size += dataSize;
      if (!getDataList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      dataMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufmg.dcc.latin.grpc.learner.SimilarityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code learner.SimilarityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:learner.SimilarityResponse)
      br.ufmg.dcc.latin.grpc.learner.SimilarityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.class, br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.Builder.class);
    }

    // Construct using br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      rows_ = 0;

      cols_ = 0;

      data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityResponse_descriptor;
    }

    public br.ufmg.dcc.latin.grpc.learner.SimilarityResponse getDefaultInstanceForType() {
      return br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.getDefaultInstance();
    }

    public br.ufmg.dcc.latin.grpc.learner.SimilarityResponse build() {
      br.ufmg.dcc.latin.grpc.learner.SimilarityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public br.ufmg.dcc.latin.grpc.learner.SimilarityResponse buildPartial() {
      br.ufmg.dcc.latin.grpc.learner.SimilarityResponse result = new br.ufmg.dcc.latin.grpc.learner.SimilarityResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.rows_ = rows_;
      result.cols_ = cols_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = java.util.Collections.unmodifiableList(data_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.data_ = data_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufmg.dcc.latin.grpc.learner.SimilarityResponse) {
        return mergeFrom((br.ufmg.dcc.latin.grpc.learner.SimilarityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufmg.dcc.latin.grpc.learner.SimilarityResponse other) {
      if (other == br.ufmg.dcc.latin.grpc.learner.SimilarityResponse.getDefaultInstance()) return this;
      if (other.getRows() != 0) {
        setRows(other.getRows());
      }
      if (other.getCols() != 0) {
        setCols(other.getCols());
      }
      if (!other.data_.isEmpty()) {
        if (data_.isEmpty()) {
          data_ = other.data_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDataIsMutable();
          data_.addAll(other.data_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufmg.dcc.latin.grpc.learner.SimilarityResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufmg.dcc.latin.grpc.learner.SimilarityResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int rows_ ;
    /**
     * <code>optional int32 rows = 1;</code>
     */
    public int getRows() {
      return rows_;
    }
    /**
     * <code>optional int32 rows = 1;</code>
     */
    public Builder setRows(int value) {
      
      rows_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 rows = 1;</code>
     */
    public Builder clearRows() {
      
      rows_ = 0;
      onChanged();
      return this;
    }

    private int cols_ ;
    /**
     * <code>optional int32 cols = 2;</code>
     */
    public int getCols() {
      return cols_;
    }
    /**
     * <code>optional int32 cols = 2;</code>
     */
    public Builder setCols(int value) {
      
      cols_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cols = 2;</code>
     */
    public Builder clearCols() {
      
      cols_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Double> data_ = java.util.Collections.emptyList();
    private void ensureDataIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        data_ = new java.util.ArrayList<java.lang.Double>(data_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getDataList() {
      return java.util.Collections.unmodifiableList(data_);
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public double getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public Builder setData(
        int index, double value) {
      ensureDataIsMutable();
      data_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public Builder addData(double value) {
      ensureDataIsMutable();
      data_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public Builder addAllData(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, data_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double data = 3 [packed = true];</code>
     */
    public Builder clearData() {
      data_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:learner.SimilarityResponse)
  }

  // @@protoc_insertion_point(class_scope:learner.SimilarityResponse)
  private static final br.ufmg.dcc.latin.grpc.learner.SimilarityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufmg.dcc.latin.grpc.learner.SimilarityResponse();
  }

  public static br.ufmg.dcc.latin.grpc.learner.SimilarityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SimilarityResponse>
      PARSER = new com.google.protobuf.AbstractParser<SimilarityResponse>() {
    public SimilarityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimilarityResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SimilarityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SimilarityResponse> getParserForType() {
    return PARSER;
  }

  public br.ufmg.dcc.latin.grpc.learner.SimilarityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

