// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

/**
 * Protobuf type {@code learner.SimilarityRequest}
 */
public  final class SimilarityRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:learner.SimilarityRequest)
    SimilarityRequestOrBuilder {
  // Use SimilarityRequest.newBuilder() to construct.
  private SimilarityRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SimilarityRequest() {
    labels_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SimilarityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              labels_ = new java.util.ArrayList<br.ufmg.dcc.latin.grpc.learner.Label>();
              mutable_bitField0_ |= 0x00000001;
            }
            labels_.add(input.readMessage(br.ufmg.dcc.latin.grpc.learner.Label.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        labels_ = java.util.Collections.unmodifiableList(labels_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.class, br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.Builder.class);
  }

  public static final int LABELS_FIELD_NUMBER = 1;
  private java.util.List<br.ufmg.dcc.latin.grpc.learner.Label> labels_;
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  public java.util.List<br.ufmg.dcc.latin.grpc.learner.Label> getLabelsList() {
    return labels_;
  }
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  public java.util.List<? extends br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder> 
      getLabelsOrBuilderList() {
    return labels_;
  }
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  public br.ufmg.dcc.latin.grpc.learner.Label getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  public br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder getLabelsOrBuilder(
      int index) {
    return labels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < labels_.size(); i++) {
      output.writeMessage(1, labels_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < labels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, labels_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ufmg.dcc.latin.grpc.learner.SimilarityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code learner.SimilarityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:learner.SimilarityRequest)
      br.ufmg.dcc.latin.grpc.learner.SimilarityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.class, br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.Builder.class);
    }

    // Construct using br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getLabelsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        labelsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ufmg.dcc.latin.grpc.learner.LearnerProto.internal_static_learner_SimilarityRequest_descriptor;
    }

    public br.ufmg.dcc.latin.grpc.learner.SimilarityRequest getDefaultInstanceForType() {
      return br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.getDefaultInstance();
    }

    public br.ufmg.dcc.latin.grpc.learner.SimilarityRequest build() {
      br.ufmg.dcc.latin.grpc.learner.SimilarityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public br.ufmg.dcc.latin.grpc.learner.SimilarityRequest buildPartial() {
      br.ufmg.dcc.latin.grpc.learner.SimilarityRequest result = new br.ufmg.dcc.latin.grpc.learner.SimilarityRequest(this);
      int from_bitField0_ = bitField0_;
      if (labelsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.labels_ = labels_;
      } else {
        result.labels_ = labelsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ufmg.dcc.latin.grpc.learner.SimilarityRequest) {
        return mergeFrom((br.ufmg.dcc.latin.grpc.learner.SimilarityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ufmg.dcc.latin.grpc.learner.SimilarityRequest other) {
      if (other == br.ufmg.dcc.latin.grpc.learner.SimilarityRequest.getDefaultInstance()) return this;
      if (labelsBuilder_ == null) {
        if (!other.labels_.isEmpty()) {
          if (labels_.isEmpty()) {
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLabelsIsMutable();
            labels_.addAll(other.labels_);
          }
          onChanged();
        }
      } else {
        if (!other.labels_.isEmpty()) {
          if (labelsBuilder_.isEmpty()) {
            labelsBuilder_.dispose();
            labelsBuilder_ = null;
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000001);
            labelsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLabelsFieldBuilder() : null;
          } else {
            labelsBuilder_.addAllMessages(other.labels_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ufmg.dcc.latin.grpc.learner.SimilarityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ufmg.dcc.latin.grpc.learner.SimilarityRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<br.ufmg.dcc.latin.grpc.learner.Label> labels_ =
      java.util.Collections.emptyList();
    private void ensureLabelsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        labels_ = new java.util.ArrayList<br.ufmg.dcc.latin.grpc.learner.Label>(labels_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        br.ufmg.dcc.latin.grpc.learner.Label, br.ufmg.dcc.latin.grpc.learner.Label.Builder, br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder> labelsBuilder_;

    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public java.util.List<br.ufmg.dcc.latin.grpc.learner.Label> getLabelsList() {
      if (labelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(labels_);
      } else {
        return labelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public int getLabelsCount() {
      if (labelsBuilder_ == null) {
        return labels_.size();
      } else {
        return labelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Label getLabels(int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);
      } else {
        return labelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder setLabels(
        int index, br.ufmg.dcc.latin.grpc.learner.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.set(index, value);
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder setLabels(
        int index, br.ufmg.dcc.latin.grpc.learner.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.set(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder addLabels(br.ufmg.dcc.latin.grpc.learner.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder addLabels(
        int index, br.ufmg.dcc.latin.grpc.learner.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(index, value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder addLabels(
        br.ufmg.dcc.latin.grpc.learner.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder addLabels(
        int index, br.ufmg.dcc.latin.grpc.learner.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder addAllLabels(
        java.lang.Iterable<? extends br.ufmg.dcc.latin.grpc.learner.Label> values) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, labels_);
        onChanged();
      } else {
        labelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder clearLabels() {
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        labelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public Builder removeLabels(int index) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.remove(index);
        onChanged();
      } else {
        labelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Label.Builder getLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder getLabelsOrBuilder(
        int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);  } else {
        return labelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public java.util.List<? extends br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder> 
         getLabelsOrBuilderList() {
      if (labelsBuilder_ != null) {
        return labelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(labels_);
      }
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Label.Builder addLabelsBuilder() {
      return getLabelsFieldBuilder().addBuilder(
          br.ufmg.dcc.latin.grpc.learner.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public br.ufmg.dcc.latin.grpc.learner.Label.Builder addLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().addBuilder(
          index, br.ufmg.dcc.latin.grpc.learner.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .learner.Label labels = 1;</code>
     */
    public java.util.List<br.ufmg.dcc.latin.grpc.learner.Label.Builder> 
         getLabelsBuilderList() {
      return getLabelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        br.ufmg.dcc.latin.grpc.learner.Label, br.ufmg.dcc.latin.grpc.learner.Label.Builder, br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder> 
        getLabelsFieldBuilder() {
      if (labelsBuilder_ == null) {
        labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            br.ufmg.dcc.latin.grpc.learner.Label, br.ufmg.dcc.latin.grpc.learner.Label.Builder, br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder>(
                labels_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        labels_ = null;
      }
      return labelsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:learner.SimilarityRequest)
  }

  // @@protoc_insertion_point(class_scope:learner.SimilarityRequest)
  private static final br.ufmg.dcc.latin.grpc.learner.SimilarityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ufmg.dcc.latin.grpc.learner.SimilarityRequest();
  }

  public static br.ufmg.dcc.latin.grpc.learner.SimilarityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SimilarityRequest>
      PARSER = new com.google.protobuf.AbstractParser<SimilarityRequest>() {
    public SimilarityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimilarityRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SimilarityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SimilarityRequest> getParserForType() {
    return PARSER;
  }

  public br.ufmg.dcc.latin.grpc.learner.SimilarityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

