// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public interface SimilarityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learner.SimilarityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  java.util.List<br.ufmg.dcc.latin.grpc.learner.Label> 
      getLabelsList();
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  br.ufmg.dcc.latin.grpc.learner.Label getLabels(int index);
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  int getLabelsCount();
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  java.util.List<? extends br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder> 
      getLabelsOrBuilderList();
  /**
   * <code>repeated .learner.Label labels = 1;</code>
   */
  br.ufmg.dcc.latin.grpc.learner.LabelOrBuilder getLabelsOrBuilder(
      int index);
}
