// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: learner.proto

package br.ufmg.dcc.latin.grpc.learner;

public interface SimilarityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:learner.SimilarityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 rows = 1;</code>
   */
  int getRows();

  /**
   * <code>optional int32 cols = 2;</code>
   */
  int getCols();

  /**
   * <code>repeated double data = 3 [packed = true];</code>
   */
  java.util.List<java.lang.Double> getDataList();
  /**
   * <code>repeated double data = 3 [packed = true];</code>
   */
  int getDataCount();
  /**
   * <code>repeated double data = 3 [packed = true];</code>
   */
  double getData(int index);
}
